name: "POI API - CD"

on:
  registry_package:
    types: [published,updated]

env:
  AZURE_WEBAPP_NAME: openhackp80414l2poi
  dockerRegistry: "docker.pkg.github.com/dariuszporowski/devops-openhack-v2-dryrun"
  dockerImageName: "api-poi"
  
jobs:
  poi-api-cd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Azure authentication
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Deploy to Azure Web App for Container'   
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} 
        images: ${{ env.dockerRegistry }}/${{ env.dockerImageName }}
