name: "POI API - CI/CD"

on:
  push:
    branches: [openhack_refresh]
    paths: "apis/poi/web/**"

env:
  gitHubOwner: dariuszporowski
  gitHubRepositoryName: devops-openhack-v2-dryrun
  dockerRegistry: docker.pkg.github.com
  dockerImageName: api-poi
  AZURE_WEBAPP_NAME: openhackp80414l2poi
  AZURE_WEBAPP_RG: openhackp80414l2rg

jobs:
  poi-api-cicd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          path: "./apis/poi/web"
          username: ${{ env.gitHubOwner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.dockerRegistry }}
          repository: ${{ env.gitHubOwner }}/${{ env.gitHubRepositoryName }}/${{ env.dockerImageName }}
          tags: ${{ github.run_number }}
          tag_with_ref: true
          tag_with_sha: true
      - uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # - uses: azure/docker-login@v1
      #   with:
      #     login-server: ${{ env.dockerRegistry }}
      #     username: ${{ env.gitHubOwner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - uses: azure/CLI@v1
      #   with:
      #     inlineScript: |
      #       az webapp config appsettings set --resource-group ${{ env.AZURE_WEBAPP_RG }} --name ${{ env.AZURE_WEBAPP_NAME }} --settings DOCKER_REGISTRY_SERVER_USERNAME=${{ env.gitHubOwner }} DOCKER_REGISTRY_SERVER_PASSWORD=${{ secrets.GITHUB_TOKEN }} DOCKER_REGISTRY_SERVER_URL=${{ env.dockerRegistry }} DOCKER_ENABLE_CI=true

      - name: Set Web App ACR authentication
        uses: Azure/appservice-settings@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          app-settings-json: |
            [
                {
                    "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
                    "value": "${{ secrets.GITHUB_TOKEN }}",
                    "slotSetting": false
                },
                {
                    "name": "DOCKER_REGISTRY_SERVER_URL",
                    "value": "${{ env.dockerRegistry }}",
                    "slotSetting": false
                },
                {
                    "name": "DOCKER_REGISTRY_SERVER_USERNAME",
                    "value": "${{ env.gitHubOwner }}",
                    "slotSetting": false
                },
                {
                    "name": "DOCKER_ENABLE_CI",
                    "value": "true",
                    "slotSetting": false
                }
            ]

      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: "${{ env.dockerRegistry }}/${{ env.gitHubOwner }}/${{ env.gitHubRepositoryName }}/${{ env.dockerImageName }}:${{ github.run_number }}"
