name: "POI API - CI/CD"

on:
  push:
    branches: [openhack_refresh]
    paths: "apis/poi/web/**"

env:
  gitHubOwner: dariuszporowski
  gitHubRepositoryName: devops-openhack-v2-dryrun
  dockerRegistry: docker.pkg.github.com
  dockerImageName: api-poi
  AZURE_WEBAPP_NAME: openhackp80414l2poi
  AZURE_WEBAPP_RG: openhackp80414l2rg
  workDir: "./apis/poi/web"
  slotName: "staging"
  healthcheckSuffix: "api/healthcheck/poi"

jobs:
  poi-api-cicd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image and push to registry
        uses: docker/build-push-action@v1
        with:
          path: ${{ env.workDir }}
          username: ${{ env.gitHubOwner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.dockerRegistry }}
          repository: ${{ env.gitHubOwner }}/${{ env.gitHubRepositoryName }}/${{ env.dockerImageName }}
          tags: ${{ github.run_number }}
          tag_with_ref: true
          tag_with_sha: true

      - name: Auth to Azure
        uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # - uses: azure/docker-login@v1
      #   with:
      #     login-server: ${{ env.dockerRegistry }}
      #     username: ${{ env.gitHubOwner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - uses: azure/CLI@v1
      #   with:
      #     inlineScript: |
      #       az webapp config appsettings set --resource-group ${{ env.AZURE_WEBAPP_RG }} --name ${{ env.AZURE_WEBAPP_NAME }} --settings DOCKER_REGISTRY_SERVER_USERNAME=${{ env.gitHubOwner }} DOCKER_REGISTRY_SERVER_PASSWORD=${{ secrets.GITHUB_TOKEN }} DOCKER_REGISTRY_SERVER_URL=https://${{ env.dockerRegistry }}

      - name: Set WebApp AppSettings - production
        uses: Azure/appservice-settings@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          app-settings-json: |
            [
                {
                    "name": "WEBSITE_ADD_SITENAME_BINDINGS_IN_APPHOST_CONFIG",
                    "value": "1",
                    "slotSetting": false
                }
            ]

      - name: Set WebApp AppSettings - {{ env.slotName }}
        uses: Azure/appservice-settings@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: ${{ env.slotName }}
          app-settings-json: |
            [
                {
                    "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
                    "value": "${{ secrets.DOCKER_PULL_PAT }}",
                    "slotSetting": false
                },
                {
                    "name": "DOCKER_REGISTRY_SERVER_URL",
                    "value": "https://${{ env.dockerRegistry }}",
                    "slotSetting": false
                },
                {
                    "name": "DOCKER_REGISTRY_SERVER_USERNAME",
                    "value": "${{ env.gitHubOwner }}",
                    "slotSetting": false
                },
                {
                    "name": "WEBSITE_SWAP_WARMUP_PING_PATH",
                    "value": "/${{ env.healthcheckSuffix }}",
                    "slotSetting": false
                },
                {
                    "name": "WEBSITE_SWAP_WARMUP_PING_STATUSES",
                    "value": "200",
                    "slotSetting": false
                },
                {
                    "name": "WEBSITE_ADD_SITENAME_BINDINGS_IN_APPHOST_CONFIG",
                    "value": "1",
                    "slotSetting": false
                }
            ]
          general-settings-json: '{"autoSwapSlotName": "production"}'

      - name: Deploy WebApp
        # uses: azure/webapps-deploy@v2
        uses: azure/webapps-container-deploy@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: ${{ env.slotName }}
          images: "${{ env.dockerRegistry }}/${{ env.gitHubOwner }}/${{ env.gitHubRepositoryName }}/${{ env.dockerImageName }}:${{ github.run_number }}"

      # - name: Check 200
      #   run: |
      #     while [[ $(./polling.sh https://${{ env.AZURE_WEBAPP_NAME }}-${{ env.slotName }}.azurewebsites.net/${{ env.healthcheckSuffix }}) != "200" ]]; do
      #       echo 0 >/dev/null
      #       sleep 2
      #     done
      #   working-directory: "./.github/workflows"

      # - uses: azure/CLI@v1
      #   with:
      #     inlineScript: |
      #       az webapp deployment slot swap -g ${{ env.AZURE_WEBAPP_RG }} -n ${{ env.AZURE_WEBAPP_NAME }} --slot ${{ env.slotName }} --target-slot production
