name: "POI API - PR"

on:
  pull_request:
    branches: [ openhack_refresh ]

defaults:
  run:
    working-directory: "/apis/poi/web"

env:
  dotnetVersion: "3.1.101"

jobs:
  pr:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.dotnetVersion }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: "apis/poi/tests/UnitTests"
